# Generated by Django 5.1.3 on 2024-12-03 15:04

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/actors/image')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/events/main_image/')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventImportant',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/events/main_events')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='important', to='home.events', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Important Event',
                'verbose_name_plural': 'Important Events',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.events')),
            ],
        ),
        migrations.CreateModel(
            name='EventActors',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.actors')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.events')),
            ],
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.events')),
            ],
        ),
    ]
