# Generated by Django 5.1.3 on 2024-12-17 18:19

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10)),
                ('event_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='home.eventtime')),
            ],
            options={
                'ordering': ['row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.CharField(default=home.models.generate_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
